/* Accessible SVG plots and daily reflection navigation; journal data stays unchanged. */
function axisMoney(v){return new Intl.NumberFormat('de-DE',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2}).format(v);}
function shortDate(d){return d.slice(8,10)+'.'+d.slice(5,7)+'.';}
function performanceChartHTML(trades,id,mode='cumulative'){
  const all=F.performanceSeries(trades),rows=all.slice(-30);if(!rows.length)return '<div class="empty">Noch keine Trades. Nach dem ersten Trade erscheint hier dein Verlauf mit Dollar-Skala.</div>';
  const opening=rows[0].cumulative-rows[0].daily,values=mode==='daily'?rows.map(r=>r.daily):[opening,...rows.map(r=>r.cumulative)],scale=F.niceScale(values),W=620,H=290,L=82,R=22,T=24,B=48,pw=W-L-R,ph=H-T-B;
  const y=v=>T+(scale.max-v)/(scale.max-scale.min)*ph,slots=mode==='daily'?rows.length:rows.length+1,x=i=>L+pw*(mode==='daily'?(i+.5)/slots:i/(slots-1));
  const grid=scale.ticks.map(v=>`<g><line x1="${L}" x2="${W-R}" y1="${y(v)}" y2="${y(v)}" class="${v===0?'plot-zero':'plot-grid'}"/><text x="${L-12}" y="${y(v)+4}" text-anchor="end" class="plot-label">${esc(axisMoney(v))}</text></g>`).join('');
  const path=values.map((v,i)=>(i?'L':'M')+x(i).toFixed(2)+' '+y(v).toFixed(2)).join(' ');
  const marks=rows.map((r,i)=>{const value=mode==='daily'?r.daily:r.cumulative,px=x(mode==='daily'?i:i+1),py=y(value),w=Math.max(3,Math.min(32,pw/rows.length*.58));return `<g class="plot-point" tabindex="0" role="button" aria-label="${esc(r.date+' · '+money(value))}" onclick="selectPerformancePoint('${id}','${r.date}')" onfocus="selectPerformancePoint('${id}','${r.date}')" onmouseenter="selectPerformancePoint('${id}','${r.date}')" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();selectPerformancePoint('${id}','${r.date}')}"><title>${esc(r.date+' · Tages-P&L '+money(r.daily)+' · Gesamt '+money(r.cumulative))}</title>${mode==='daily'?`<rect x="${px-w/2}" y="${Math.min(py,y(0))}" width="${w}" height="${Math.max(2,Math.abs(py-y(0)))}" rx="3" class="${value<0?'plot-negative':'plot-positive'}"/>`:`<circle cx="${px}" cy="${py}" r="4" class="plot-dot"/>`}<circle cx="${px}" cy="${py}" r="16" fill="transparent" class="plot-hit"/></g>`;}).join('');
  const labelIndices=[...new Set([0,Math.floor((rows.length-1)/2),rows.length-1])];
  const dates=labelIndices.map(i=>`<text x="${x(mode==='daily'?i:i+1)}" y="${H-15}" text-anchor="${i===rows.length-1?'end':i===0?'start':'middle'}" class="plot-label">${shortDate(rows[i].date)}</text>`).join('');
  const last=rows.at(-1);return `<div class="plot-summary"><div><span>Gesamt-P&L</span><strong class="${cls(last.cumulative)}">${money(last.cumulative)}</strong></div><div><span>Handelstage</span><strong>${all.length}</strong></div><div><span>Max. Drawdown</span><strong>${money(-F.metrics(trades).drawdown)}</strong></div></div><p class="small plot-caption">USD · ${mode==='daily'?'Tagesergebnisse':'Kumulierter Verlauf ab dem ersten Trade'} · ${rows[0].date} bis ${last.date}${all.length>30?' · letzte 30 Handelstage':''}</p><div class="plot-scroll" tabindex="0" aria-label="Performance-Diagramm horizontal scrollen"><svg class="performance-svg" viewBox="0 0 ${W} ${H}" role="group" aria-label="${mode==='daily'?'Tagesergebnisse':'Kumulierte Performance'} mit Dollar-Skala und Nulllinie">${grid}${mode==='daily'?'':`<path d="${path} L${x(values.length-1)} ${y(0)} L${x(0)} ${y(0)} Z" class="plot-area"/><path d="${path}" class="plot-line"/>`}${marks}${dates}<text x="${L}" y="14" class="plot-label">USD</text></svg></div><div class="plot-inspect"><div class="field"><label for="${id}Date">Handelstag ansehen</label><select id="${id}Date" onchange="selectPerformancePoint('${id}',this.value)">${[...rows].reverse().map(r=>`<option value="${r.date}">${r.date}</option>`).join('')}</select></div><div id="${id}Readout" class="plot-readout" aria-live="polite">${performanceReadout(last)}</div></div>`;
}
function performanceReadout(r){return `<b>${esc(r.date)}</b><span>Tages-P&L <strong class="${cls(r.daily)}">${money(r.daily)}</strong></span><span>Kumuliert <strong class="${cls(r.cumulative)}">${money(r.cumulative)}</strong></span><span>${r.count} ${r.count===1?'Trade':'Trades'}</span>`;}
function selectPerformancePoint(id,date){const r=F.performanceSeries(id==='statsChart'?statsTrades():data.trades).find(r=>r.date===date);if(!r)return;document.getElementById(id+'Readout').innerHTML=performanceReadout(r);document.getElementById(id+'Date').value=date;}
function renderCategoryChart(id,rows){
  const el=document.getElementById(id);if(!rows.length){el.innerHTML='<div class="empty">Noch keine Daten.</div>';return;}const limit=F.niceScale(rows.flatMap(r=>[-Math.abs(r.pnl),Math.abs(r.pnl)])).max;
  el.innerHTML=`<div class="category-scale" aria-label="Dollar-Skala"><span>${esc(axisMoney(-limit))}</span><span>0 USD</span><span>${esc(axisMoney(limit))}</span></div>`+rows.map(r=>`<div class="category-row"><div class="category-heading"><span><b>${esc(r.name||'Nicht dokumentiert')}</b><small>${r.count} Trades${r.winrate===undefined?'':' · '+Math.round(r.winrate)+'% Winrate'}</small></span><strong class="${cls(r.pnl)}">${money(r.pnl)}</strong></div><div class="category-track" role="img" aria-label="${esc((r.name||'Nicht dokumentiert')+': '+money(r.pnl))}"><span class="category-zero"></span><span class="category-bar ${r.pnl<0?'plot-negative':'plot-positive'}" style="left:${r.pnl<0?50-Math.abs(r.pnl)/limit*50:50}%;width:${Math.abs(r.pnl)/limit*50}%"></span></div></div>`).join('');
}
let dailyEditingDate='',dailyLoadedText='',dailyDrafts=new Map(),dailyHistoryLimit=30;
function rememberDailyDraft(){const el=document.getElementById('dailyText');if(dailyEditingDate){if(el.value!==dailyLoadedText)dailyDrafts.set(dailyEditingDate,el.value);else dailyDrafts.delete(dailyEditingDate);}}
function resetDailyEditor(){dailyEditingDate='';dailyLoadedText='';dailyDrafts.clear();dailyHistoryLimit=30;document.getElementById('dailySearch').value='';document.getElementById('dailyHistory').innerHTML='';document.getElementById('dailyDate').value='';}
function loadDailyEditor(date){rememberDailyDraft();if(dailyEditingDate!==date||document.getElementById('dailyText').value===dailyLoadedText){dailyEditingDate=date;dailyLoadedText=data.daily[date]||'';document.getElementById('dailyText').value=dailyDrafts.has(date)?dailyDrafts.get(date):dailyLoadedText;}}
function openDailyReflection(date){if(!F.validDate(date))return;document.getElementById('dailyDate').value=date;renderDaily();document.getElementById('dailyText').focus();}
function renderDailyHistory(){
  const q=document.getElementById('dailySearch').value.trim().toLowerCase(),rows=Object.entries(data.daily).filter(([date,text])=>F.validDate(date)&&typeof text==='string'&&text.trim()&&(!q||(date+' '+shortDate(date)+' '+text).toLowerCase().includes(q))).sort(([a],[b])=>b.localeCompare(a)),el=document.getElementById('dailyHistory');
  document.getElementById('dailyHistoryCount').textContent=rows.length+' Reflexionen';el.innerHTML=rows.length?rows.slice(0,dailyHistoryLimit).map(([date,text])=>`<button type="button" class="reflection-entry" aria-pressed="${document.getElementById('dailyDate').value===date}" onclick="openDailyReflection('${date}')"><span><b>${date}</b><span class="reflection-preview">${esc(text.slice(0,180))}</span></span><span class="small">Öffnen</span></button>`).join(''):'<div class="empty">'+(q?'Keine passende Reflexion gefunden.':'Noch keine Tagesreflexion gespeichert.')+'</div>';document.getElementById('dailyHistoryMore').hidden=rows.length<=dailyHistoryLimit;
}
