/* Journal workflows. DOM handlers initialize after the original app has loaded. */
const F=JournalFeatures;
let editingTrade=null,detailTrade=null,csvDraft=null,tradePage=0,coachEpoch=0,coachLists={outgoing:[],incoming:[]};
const proGet=id=>document.getElementById(id);
const proValue=id=>proGet(id)?.value||'';
const proIcon=name=>`<svg class="icon" aria-hidden="true"><use href="#i-${name}"/></svg>`;
const proNumber=(n,d=2)=>n===null||n===undefined?'—':n===Infinity?'∞':Number(n).toLocaleString('de-DE',{maximumFractionDigits:d,minimumFractionDigits:d});
const proMetric=(label,value,sub='')=>`<div class="card metric"><span class="kpi-label">${label}</span><div class="kpi">${value}</div>${sub?`<p class="small">${sub}</p>`:''}</div>`;
function captureTradeExtras(){const risk=proValue('riskT');return {risk:risk?Number(risk):null,fees:Number(proValue('feesT'))||0,setup:proValue('setupT').trim()||'IFVG',preflight:Object.fromEntries(F.checklist.map(([key])=>[key,!!proGet('preflight-'+key)?.checked])),setupNotes:proValue('setupNotes').trim()};}
function updatePreflight(){const n=F.checklist.filter(([key])=>proGet('preflight-'+key)?.checked).length;proGet('preflightCount').textContent=n+' / '+F.checklist.length+' dokumentiert';proGet('preflightProgress').value=n;}
function beginTradeEdit(id){const t=data.trades.find(t=>t.id===id);if(!t)return;proGet('tradeDetailDialog').close();editingTrade={id,owner:data.ownerId,base:J.clone(t)};show('trade');const form=proGet('tradeForm');form.reset();fillAccounts();
  const fields={dateT:t.date,timeT:t.time,accT:t.accountId,market:t.market,dir:t.direction,pnl:t.pnl,bias:t.bias,htf:t.htf,sweep:t.sweep,before:t.before,after:t.after,plan:t.plan,violation:t.violation,note:t.note,riskT:t.risk??'',feesT:t.fees||0,setupT:t.setup||'IFVG',setupNotes:t.setupNotes||''};
  for(const [id,value] of Object.entries(fields)){const el=proGet(id);if(el.tagName==='SELECT'&&value&&!Array.from(el.options).some(x=>x.value===String(value)))el.add(new Option(value,value));el.value=value??'';}
  document.querySelectorAll('#tradeForm [data-k]').forEach(c=>c.checked=(t[c.dataset.k]||[]).includes(c.value));for(const [key] of F.checklist)proGet('preflight-'+key).checked=!!t.preflight?.[key];
  proGet('tradeHeading').textContent='Trade bearbeiten';proGet('cancelTradeEdit').hidden=false;proGet('removeTradeImage').hidden=!t.image;proGet('clearTradeImage').checked=false;updatePreflight();updateSession();
}
function finishTradeEdit(){editingTrade=null;proGet('tradeHeading').textContent='Trade erfassen';proGet('cancelTradeEdit').hidden=true;proGet('removeTradeImage').hidden=true;proGet('tradeForm').reset();proGet('dateT').value=iso();proGet('timeT').value=berlinTime();updateSession();updatePreflight();}
function cancelTradeEditing(){finishTradeEdit();show('trades');}
function safeImage(value){return typeof value==='string'&&(/^data:image\/(png|jpeg|webp|gif);base64,[a-z0-9+/=\s]+$/i.test(value)||/^https:\/\//i.test(value))?value:'';}
function tradeDetailsHTML(t,{coach=false}={}){
  const r=F.multiple(t),checked=F.checklist.filter(([key])=>t.preflight?.[key]),img=safeImage(t.image);
  return `<div class="grid three detail-kpis">${proMetric('P&L netto',money(t.pnl))}${proMetric('Geplantes Risiko',t.risk?money(t.risk):'Nicht hinterlegt')}${proMetric('Ergebnis in R',r===null?'—':proNumber(r)+' R')}</div><dl class="detail-list"><div><dt>Datum / Uhrzeit</dt><dd>${esc(t.date)} · ${esc(t.time||'—')}</dd></div>${coach?'':`<div><dt>Konto</dt><dd>${esc(accName(t.accountId))}</dd></div>`}<div><dt>Markt / Richtung</dt><dd>${esc(t.market)} · ${esc(t.direction||'—')}</dd></div><div><dt>Session / Setup</dt><dd>${esc(t.session||'—')} · ${esc(t.setup||'IFVG')}</dd></div><div><dt>Bias / HTF</dt><dd>${esc(t.bias||'—')} · ${esc(t.htf||'—')}</dd></div><div><dt>Gebühren</dt><dd>${money(t.fees||0)}</dd></div></dl><details class="review-fold" open><summary>Setup-Dokumentation</summary><div class="checklist-read">${F.checklist.map(([key,label])=>`<div>${proIcon(t.preflight?.[key]?'check':'info')}<span>${label}</span><span class="small">${t.preflight?.[key]?'Dokumentiert':'Offen'}</span></div>`).join('')}</div><p class="small">${checked.length} / ${F.checklist.length} Kriterien dokumentiert</p><dl class="detail-list">${['liquidity','structure','ifvg','confirmation'].map(k=>`<div><dt>${({liquidity:'Liquidität',structure:'Struktur',ifvg:'IFVG',confirmation:'Confirmation'})[k]}</dt><dd>${esc((t[k]||[]).join(', ')||'—')}</dd></div>`).join('')}</dl></details>${'before' in t?`<div class="card inner-card"><h3>Psychologie & Plan</h3><p>${esc(t.before||'—')} → ${esc(t.after||'—')}</p><p class="small">Plan: ${esc(t.plan||'—')} · Regelverletzung: ${esc(t.violation||'Keine')}</p></div>`:''}${t.setupNotes?`<div class="card inner-card"><h3>Setup-Notizen</h3><p class="preserve-text">${esc(t.setupNotes)}</p></div>`:''}${t.note?`<div class="card inner-card"><h3>Reflexion</h3><p class="preserve-text">${esc(t.note)}</p></div>`:''}${img?`<button type="button" class="chart-preview btn ghost" onclick="zoomTradeImage(this.querySelector('img').src)"><img src="${esc(img)}" alt="Chart-Screenshot zum Trade" loading="lazy" referrerpolicy="no-referrer"><span class="small">Screenshot vergrößern</span></button>`:''}`;
}
function zoomTradeImage(src){const safe=safeImage(src);if(!safe)return;proGet('zoomImage').src=safe;proGet('imageZoomDialog').showModal();}
function openTradeDetail(id){const t=data.trades.find(t=>t.id===id);if(!t)return;detailTrade={id,owner:data.ownerId};proGet('tradeDetailTitle').textContent=t.market+' · '+t.date;proGet('tradeDetailBody').innerHTML=tradeDetailsHTML(t);proGet('tradeDetailDialog').showModal();}
function currentFilters(){return {search:proValue('tradeSearch'),account:proValue('filterAccount'),from:proValue('filterFrom'),to:proValue('filterTo'),market:proValue('filterMarket'),session:proValue('filterSession'),setup:proValue('filterSetup')};}
function fillFilter(id,values,label){const el=proGet(id),selected=el.value;el.innerHTML=`<option value="">${label}</option>`+values.map(x=>`<option value="${esc(x.value??x)}">${esc(x.label??x)}</option>`).join('');el.value=selected;}
function renderProTrades(){
  fillFilter('filterAccount',data.accounts.map(a=>({value:a.id,label:a.name})),'Alle Konten');fillFilter('filterMarket',[...new Set(data.trades.map(t=>t.market))].sort(),'Alle Märkte');fillFilter('filterSession',[...new Set(data.trades.map(t=>t.session).filter(Boolean))].sort(),'Alle Sessions');fillFilter('filterSetup',[...new Set(data.trades.map(t=>t.setup||'IFVG'))].sort(),'Alle Setups');
  const rows=F.filter(data.trades,currentFilters()),pages=Math.max(1,Math.ceil(rows.length/50));tradePage=Math.min(tradePage,pages-1);const page=rows.slice(tradePage*50,(tradePage+1)*50),m=F.metrics(rows);
  proGet('tradeInfo').textContent=rows.length+' / '+data.trades.length+' Trades';proGet('filterSummary').textContent=money(m.pnl)+' · '+Math.round(m.winrate)+'% Winrate';
  proGet('tradeTable').innerHTML=rows.length?`<div class="table-scroll"><table><thead><tr><th>Datum</th><th>Konto</th><th>Markt</th><th>Setup</th><th>P&L</th><th>R</th><th>Aktionen</th></tr></thead><tbody>${page.map(t=>`<tr><td>${esc(t.date)}<br><span class="small">${esc(t.time)}</span></td><td>${esc(accName(t.accountId))}</td><td>${esc(t.market)}<br><span class="small">${esc(t.direction)}</span></td><td>${esc(t.setup||'IFVG')}</td><td class="${cls(t.pnl)}"><b>${money(t.pnl)}</b></td><td>${F.multiple(t)===null?'—':proNumber(F.multiple(t))+' R'}</td><td class="row-actions"><button class="btn secondary" onclick="openTradeDetail('${t.id}')">Details</button><button class="btn danger" onclick="delTrade('${t.id}')">Löschen</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Keine Trades für diese Auswahl.</div>';
  proGet('tradePagination').innerHTML=rows.length>50?`<button class="btn ghost" ${tradePage===0?'disabled':''} onclick="tradePage--;renderProTrades()">Zurück</button><span class="small">Seite ${tradePage+1} / ${pages}</span><button class="btn ghost" ${tradePage===pages-1?'disabled':''} onclick="tradePage++;renderProTrades()">Weiter</button>`:'';
}
function resetTradeFilters(){document.querySelectorAll('#tradeFilters input,#tradeFilters select').forEach(e=>e.value='');tradePage=0;renderProTrades();}
function renderRiskStats(){const m=F.metrics(data.trades);proGet('riskMetrics').innerHTML=proMetric('Profit-Faktor',proNumber(m.profitFactor))+proMetric('Ø Ergebnis / Trade',m.expectancy===null?'—':money(m.expectancy))+proMetric('Max. Drawdown',money(-m.drawdown),'Realisierte Trade-Ergebnisse')+proMetric('Ø Ergebnis in R',m.averageR===null?'—':proNumber(m.averageR)+' R',m.rCount+' / '+m.count+' Trades mit Risiko')+proMetric('Längste Verlustserie',String(m.maxLossStreak))+proMetric('Plan eingehalten',m.planRate===null?'—':Math.round(m.planRate)+'%',m.planCount+' Trades mit Plan-Angabe');}
function renderWeekly(){
  const date=F.validDate(proValue('weekDate'))?proValue('weekDate'):iso();if(!proValue('weekDate'))proGet('weekDate').value=date;const w=F.week(date),rows=F.weekTrades(data.trades,date),m=F.metrics(rows),violations=rows.filter(t=>t.violation),sessions=F.groups(rows,'session'),emotions=F.groups(rows,'before');
  proGet('weekPeriod').textContent=w.start+' bis '+w.end;proGet('weekMetrics').innerHTML=proMetric('Wochen-P&L',money(m.pnl))+proMetric('Trades',String(m.count))+proMetric('Regelverletzungen',String(violations.length))+proMetric('Ø R',m.averageR===null?'—':proNumber(m.averageR)+' R',m.rCount+' Trades mit Risiko');
  const groupHTML=groups=>groups.map(g=>`<div class="session"><span>${esc(g.name)}<br><span class="small">${g.count} Trades · ${Math.round(g.winrate)}% Winrate</span></span><b class="${cls(g.pnl)}">${money(g.pnl)}</b></div>`).join('')||'<div class="empty">Keine Trades in dieser Woche.</div>';
  proGet('weekSessions').innerHTML=groupHTML(sessions);proGet('weekEmotions').innerHTML=groupHTML(emotions);proGet('weekViolations').innerHTML=violations.map(t=>`<button class="review-trade" onclick="openTradeDetail('${t.id}')"><span>${esc(t.date)} · ${esc(t.market)} · ${esc(t.violation)}</span><b class="${cls(t.pnl)}">${money(t.pnl)}</b></button>`).join('')||'<p class="small">Keine Regelverletzungen dokumentiert.</p>';
  proGet('weekReflection').value=data.reviews?.[w.start]?.reflection||'';proGet('weekFocus').value=data.reviews?.[w.start]?.focus||'';weeklyContext={owner:data.ownerId,week:w.start,base:{reflection:'',focus:'',...J.clone(data.reviews?.[w.start]||{})}};
}
function saveWeekly(){const w=F.week(proValue('weekDate')||iso());data.reviews=data.reviews||{};const base=weeklyContext?.owner===data.ownerId&&weeklyContext.week===w.start?weeklyContext.base:{reflection:'',focus:'',...(data.reviews[w.start]||{})},next={...base,reflection:proValue('weekReflection').trim(),focus:proValue('weekFocus').trim(),updated_at:new Date().toISOString()},current={reflection:'',focus:'',...(data.reviews[w.start]||{})},conflicts=[];data.reviews[w.start]=J.merge(base,next,current,'reviews.'+w.start,conflicts);weeklyContext={owner:data.ownerId,week:w.start,base:J.clone(data.reviews[w.start])};if(cloudUser)rememberConflicts(conflicts);if(save()!==false)savedToast('Wochen-Review gespeichert.');}
function downloadCSVTemplate(){const blob=new Blob(['\uFEFFDatum;Uhrzeit;Markt;Richtung;P&L;Risiko;Gebühren;Notiz;TradeId\n2026-10-06;15:35;NQ;LONG;250;250;5;IFVG Retest;demo-001\n'],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Journal-CSV-Vorlage.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function openCSVImport(){csvDraft=null;proGet('csvForm').reset();fillFilter('csvAccount',data.accounts.map(a=>({value:a.id,label:a.name})),'Konto auswählen');proGet('csvMapping').innerHTML='';proGet('csvPreview').innerHTML='<p class="small">Datei auswählen, Spalten prüfen und Vorschau erstellen.</p>';proGet('csvCommit').disabled=true;proGet('csvDialog').showModal();}
async function readCSV(){const file=proGet('csvFile').files[0];if(!file)return;if(file.size>4000000)return csvError('Bitte eine CSV unter 4 MB verwenden.');const owner=data.ownerId;proGet('csvCommit').disabled=true;csvDraft=null;try{const parsed=F.csv(await file.text());if(owner!==data.ownerId||!proGet('csvDialog').open||proGet('csvFile').files[0]!==file)return;csvDraft={owner,parsed,result:null};const guessed=F.guess(parsed.headers);proGet('csvMapping').innerHTML=Object.entries({date:'Datum *',time:'Uhrzeit',market:'Markt *',pnl:'P&L *',direction:'Richtung',risk:'Risiko',fees:'Gebühren',note:'Notiz',externalId:'Trade-ID'}).map(([key,label])=>`<div class="field"><label for="csv-${key}">${label}</label><select id="csv-${key}" data-map="${key}"><option value="-1">Nicht vorhanden</option>${parsed.headers.map((h,i)=>`<option value="${i}" ${guessed[key]===i?'selected':''}>${esc(h)}</option>`).join('')}</select></div>`).join('');proGet('csvPreview').innerHTML=`<p class="small">${parsed.rows.length} Zeilen erkannt. Datumsformate: JJJJ-MM-TT oder TT.MM.JJJJ. Uhrzeit: HH:MM.</p>`;proGet('csvCommit').disabled=true;}catch(e){if(owner!==data.ownerId||!proGet('csvDialog').open)return;csvDraft=null;csvError(e.message);}}
function csvError(message){proGet('csvPreview').innerHTML=`<p class="form-error" role="alert">${esc(message)}</p>`;proGet('csvCommit').disabled=true;}
function previewCSV(){try{if(!csvDraft)return csvError('Bitte zuerst eine CSV-Datei auswählen.');const account=proValue('csvAccount');if(!data.accounts.some(a=>a.id===account))return csvError('Bitte ein Trading-Konto auswählen.');const mapping=Object.fromEntries([...document.querySelectorAll('[data-map]')].map(el=>[el.dataset.map,Number(el.value)]));csvDraft.config={mapping,account,gross:proGet('csvGross').checked};const result=F.importRows(csvDraft.parsed,mapping,account,data.trades,{gross:csvDraft.config.gross});csvDraft.result=result;proGet('csvPreview').innerHTML=`<div class="notice">${result.trades.length} neue Trades · ${result.duplicates.length} Dubletten · ${result.errors.length} fehlerhafte Zeilen</div>${result.errors.length?`<ul class="small">${result.errors.slice(0,15).map(e=>`<li>Zeile ${e.row}: ${esc(e.message)}</li>`).join('')}</ul>`:''}<div class="table-scroll"><table><tr><th>Datum</th><th>Markt</th><th>Richtung</th><th>P&L netto</th></tr>${result.trades.slice(0,10).map(t=>`<tr><td>${t.date}</td><td>${esc(t.market)}</td><td>${esc(t.direction)}</td><td>${money(t.pnl)}</td></tr>`).join('')}</table></div><p class="small">Vorschau der ersten 10 Trades. Fehlerhafte Zeilen und Dubletten werden nicht importiert.</p>`;proGet('csvCommit').disabled=!result.trades.length;}catch(e){csvError(e.message);}}
function commitCSV(){if(!csvDraft?.result||csvDraft.owner!==data.ownerId)return;const {mapping,account,gross}=csvDraft.config;if(!data.accounts.some(a=>a.id===account))return csvError('Das ausgewählte Konto wurde entfernt.');const result=F.importRows(csvDraft.parsed,mapping,account,data.trades,{gross});if(!result.trades.length)return csvError('Keine neuen Trades vorhanden.');const now=new Date().toISOString(),batch=crypto.randomUUID();for(const t of result.trades)data.trades.push({...t,id:crypto.randomUUID(),ownerId:data.ownerId,session:session(t.time),importBatch:batch,created_at:now,updated_at:now,liquidity:[],structure:[],ifvg:[],confirmation:[]});const persisted=save();csvDraft=null;proGet('csvDialog').close();show('trades');if(persisted!==false)savedToast(result.trades.length+' Trades importiert.');}
function renderAccountGoals(){const a=data.accounts.find(a=>a.id===window.selectedAccountId);if(!a)return;const q=F.tracker(a,data.trades),progress=q.target?Math.max(0,Math.min(100,q.pnl/q.target*100)):0,days=q.requiredDays?Math.min(100,q.qualifying/q.requiredDays*100):0;
  const html=`<div class="card tracker-card"><div class="head"><div><h2>Challenge & Payout</h2><p class="small">${a.cycleStart?'Zyklus ab '+esc(a.cycleStart):'Alle dokumentierten Trades'} · frei einstellbare Ziele</p></div><button class="btn secondary" onclick="openGoalDialog('${a.id}')">Ziele einstellen</button></div><div class="grid three">${proMetric('Zyklus-P&L',money(q.pnl),q.target?'Ziel: '+money(q.target):'Gewinnziel nicht hinterlegt')}${proMetric('Qualifizierende Tage',q.qualifying+' / '+(q.requiredDays||'—'),'Ab '+money(a.qualifyingDayTarget||0)+' Tagesgewinn')}${proMetric('Auszahlungen',money(q.payoutTotal))}</div><div class="goal-progress"><label>Gewinnziel <span>${proNumber(progress,0)}%</span><progress max="100" value="${progress}"></progress></label><label>Handelstage <span>${proNumber(days,0)}%</span><progress max="100" value="${days}"></progress></label></div><div class="notice">Realisierter Max. Drawdown: ${money(-q.drawdown)}${q.drawdownLimit?' · Hinterlegte Grenze: '+money(q.drawdownLimit)+(q.drawdown>=q.drawdownLimit?' · Grenze erreicht':''):''}. Kontostand nach dokumentierten Auszahlungen: ${money(q.balance)}.</div><p class="small">Der Drawdown basiert auf abgeschlossenen Trades. Offene Positionen und firmenspezifische Intraday-Regeln sind nicht enthalten.</p><div class="head"><h3>Auszahlungen</h3><button class="btn ghost" onclick="openPayoutDialog('${a.id}')">Auszahlung erfassen</button></div>${q.payouts.length?q.payouts.sort((x,y)=>y.date.localeCompare(x.date)).map(p=>`<div class="session"><span>${esc(p.date)} · ${esc(p.note||'Auszahlung')}</span><b>${money(p.amount)}</b><button class="btn danger" onclick="removePayout('${a.id}','${p.id}')">Entfernen</button></div>`).join(''):'<p class="small">Noch keine Auszahlung dokumentiert.</p>'}</div>`;proGet('accountDetail').insertAdjacentHTML('beforeend',html);
}
let goalContext=null,payoutContext=null,weeklyContext=null;
function openGoalDialog(id){const a=data.accounts.find(a=>a.id===id);if(!a)return;goalContext={id,owner:data.ownerId,base:{profitTarget:0,requiredDays:0,qualifyingDayTarget:0,maxDrawdown:0,cycleStart:'',...J.clone(a)}};for(const [el,key] of [['goalProfit','profitTarget'],['goalDays','requiredDays'],['goalDayProfit','qualifyingDayTarget'],['goalDrawdown','maxDrawdown'],['goalStart','cycleStart']])proGet(el).value=a[key]??(key==='cycleStart'?'':0);proGet('goalDialog').showModal();}
function openPayoutDialog(id){payoutContext={id,owner:data.ownerId};proGet('payoutForm').reset();proGet('payoutDate').value=iso();proGet('payoutDialog').showModal();}
async function removePayout(accountId,id){const owner=data.ownerId;if(!await confirmAction('Diese dokumentierte Auszahlung entfernen?',{title:'Auszahlung entfernen?',label:'Entfernen',danger:true})||owner!==data.ownerId)return;const a=data.accounts.find(a=>a.id===accountId);if(!a?.payouts?.[id])return;delete a.payouts[id];a.updated_at=new Date().toISOString();if(save()!==false)savedToast('Auszahlung entfernt.');renderAccounts();}
function resetProState(){editingTrade=null;detailTrade=null;csvDraft=null;goalContext=null;payoutContext=null;weeklyContext=null;coachEpoch++;coachLists={outgoing:[],incoming:[]};const c=proGet('coachContent');if(c)c.innerHTML='';proGet('zoomImage').removeAttribute?.('src');for(const id of ['tradeDetailBody','receivedTradeBody','csvMapping','csvPreview']){const e=proGet(id);if(e)e.innerHTML='';}for(const id of ['shareForm','csvForm','goalForm','payoutForm'])proGet(id)?.reset();proGet('tradeHeading').textContent='Trade erfassen';proGet('cancelTradeEdit').hidden=true;proGet('removeTradeImage').hidden=true;for(const id of ['weekDate','weekReflection','weekFocus'])proGet(id).value='';document.querySelectorAll('#tradeFilters input,#tradeFilters select').forEach(e=>e.value='');tradePage=0;}
async function refreshCoach(){const owner=cloudUser?.id,epoch=++coachEpoch;if(!owner){proGet('coachContent').innerHTML='<div class="empty">Bitte anmelden, um Freigaben zu verwalten.</div>';return;}proGet('coachContent').innerHTML='<p class="small">Freigaben werden geladen …</p>';try{const r=await sb.rpc('coach_share_list');if(owner!==cloudUser?.id||epoch!==coachEpoch)return;if(r.error)throw r.error;coachLists=r.data;proGet('coachContent').innerHTML=`<h3>Von dir freigegeben</h3>${coachLists.outgoing.length?coachLists.outgoing.map(s=>`<div class="session"><span>${esc(s.recipient_email)}<br><span class="small">${esc(s.trade_date||'Trade entfernt')} · ${esc(s.market||'')} · ${s.include_notes?'Notizen freigegeben':'Ohne Notizen'}</span></span><button class="btn danger" onclick="revokeCoachShare('${s.id}')">Widerrufen</button></div>`).join(''):'<p class="small">Keine aktiven Freigaben.</p>'}<h3>Für dich freigegeben</h3>${coachLists.incoming.length?coachLists.incoming.map(s=>`<button class="review-trade" onclick="openReceivedTrade('${s.share_id}')"><span>${esc(s.owner_name||'Journal-Mitglied')}<br><span class="small">${esc(s.trade.date)} · ${esc(s.trade.market)}</span></span><b class="${cls(s.trade.pnl)}">${money(s.trade.pnl)}</b></button>`).join(''):'<p class="small">Noch keine Trades für dich freigegeben.</p>'}`;}catch(e){if(owner===cloudUser?.id&&epoch===coachEpoch)proGet('coachContent').innerHTML=`<p class="form-error">${esc(e.message)}</p>`;}}
function openShareDialog(){if(!detailTrade||detailTrade.owner!==data.ownerId)return;if(!cloudUser)return toast('Bitte anmelden, um diesen Trade freizugeben.','info');proGet('tradeDetailDialog').close();proGet('shareForm').reset();proGet('shareError').hidden=true;proGet('shareDialog').showModal();}
async function revokeCoachShare(id){const owner=cloudUser?.id;if(!await confirmAction('Der Coach kann diesen Trade danach nicht mehr über die App abrufen.',{title:'Freigabe widerrufen?',label:'Widerrufen',danger:true})||owner!==cloudUser?.id)return;try{const r=await sb.rpc('coach_share_revoke',{share_id:id});if(owner!==cloudUser?.id)return;if(r.error)throw r.error;if(!r.data)throw new Error('Freigabe nicht mehr vorhanden.');toast('Freigabe widerrufen.');refreshCoach();}catch(e){toast(e.message,'error');}}
async function openReceivedTrade(id){const owner=cloudUser?.id;try{const r=await sb.rpc('coach_share_read',{share_id:id});if(owner!==cloudUser?.id)return;if(r.error)throw r.error;if(!r.data)throw new Error('Diese Freigabe ist nicht mehr verfügbar.');proGet('receivedTradeTitle').textContent=(r.data.owner_name||'Journal-Mitglied')+' · '+r.data.trade.market;proGet('receivedTradeBody').innerHTML=tradeDetailsHTML(r.data.trade,{coach:true});proGet('receivedTradeDialog').showModal();}catch(e){toast(e.message,'error');refreshCoach();}}
function initPro(){
  proGet('preflightRows').innerHTML=F.checklist.map(([key,label,hint])=>`<label class="preflight-row"><input type="checkbox" id="preflight-${key}" onchange="updatePreflight()"><span><b>${label}</b><span class="small">${hint}</span></span></label>`).join('');updatePreflight();
  renderTrades=renderProTrades;const originalStats=renderStats;renderStats=()=>{originalStats();renderRiskStats();};const originalDaily=renderDaily;renderDaily=()=>{originalDaily();renderWeekly();};const originalAccount=renderAccountDetail;renderAccountDetail=()=>{originalAccount();renderAccountGoals();};
  for(const el of document.querySelectorAll('#tradeFilters input,#tradeFilters select'))el.addEventListener('input',()=>{tradePage=0;renderProTrades();});
  proGet('weekDate').onchange=()=>{if(proValue('weekDate')&&F.validDate(proValue('weekDate')))renderWeekly();};proGet('csvFile').onchange=readCSV;proGet('csvForm').addEventListener('change',e=>{if(e.target.id!=='csvFile')proGet('csvCommit').disabled=true;});
  proGet('goalForm').onsubmit=e=>{e.preventDefault();const c=goalContext,a=data.accounts.find(a=>a.id===c?.id);if(!a||c.owner!==data.ownerId)return;const vals={profitTarget:Number(proValue('goalProfit')),requiredDays:Number(proValue('goalDays')),qualifyingDayTarget:Number(proValue('goalDayProfit')),maxDrawdown:Number(proValue('goalDrawdown')),cycleStart:proValue('goalStart')};if(![vals.profitTarget,vals.requiredDays,vals.qualifyingDayTarget,vals.maxDrawdown].every(v=>Number.isFinite(v)&&v>=0)||!Number.isInteger(vals.requiredDays)||vals.cycleStart&&!F.validDate(vals.cycleStart))return;const current={profitTarget:0,requiredDays:0,qualifyingDayTarget:0,maxDrawdown:0,cycleStart:'',...a},conflicts=[];Object.assign(a,J.merge(c.base,{...c.base,...vals,updated_at:new Date().toISOString()},current,'accounts.'+a.id,conflicts));if(cloudUser)rememberConflicts(conflicts);proGet('goalDialog').close();if(save()!==false)savedToast('Kontoziele gespeichert.');renderAccounts();};
  proGet('payoutForm').onsubmit=e=>{e.preventDefault();const c=payoutContext,a=data.accounts.find(a=>a.id===c?.id),amount=Number(proValue('payoutAmount')),date=proValue('payoutDate');if(!a||c.owner!==data.ownerId||!Number.isFinite(amount)||amount<=0||!F.validDate(date))return;const id=crypto.randomUUID();a.payouts=a.payouts||{};a.payouts[id]={id,date,amount,note:proValue('payoutNote').trim(),updated_at:new Date().toISOString()};a.updated_at=new Date().toISOString();proGet('payoutDialog').close();if(save()!==false)savedToast('Auszahlung gespeichert.');renderAccounts();};
  proGet('shareForm').onsubmit=async e=>{e.preventDefault();const owner=cloudUser?.id,trade=detailTrade,button=proGet('shareSubmit');if(!owner||trade?.owner!==owner)return;button.disabled=true;try{const ok=await syncRoundTrip(false);if(owner!==cloudUser?.id||trade.owner!==data.ownerId)return;if(!ok||!J.equal(data,cloudCache.base))throw new Error('Bitte zuerst den Cloud-Abgleich abschließen.');const r=await sb.rpc('coach_share_create',{trade_id:trade.id,coach_email:proValue('coachEmail').trim(),include_notes:proGet('shareNotes').checked,include_psychology:proGet('sharePsychology').checked,include_screenshot:proGet('shareScreenshot').checked});if(owner!==cloudUser?.id)return;if(r.error)throw r.error;proGet('shareDialog').close();toast('Trade für den Coach freigegeben.');refreshCoach();}catch(e){if(owner===cloudUser?.id){proGet('shareError').textContent=e.message;proGet('shareError').hidden=false;}}finally{button.disabled=false;}};
  render();
}
document.addEventListener('DOMContentLoaded',initPro);
