const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path');
(async()=>{const proxy=process.env.HTTPS_PROXY||process.env.HTTP_PROXY;const browser=await chromium.launch({args:['--no-sandbox'],...(proxy?{proxy:{server:proxy}}:{})});try{for(const viewport of [{width:1440,height:900},{width:390,height:844},{width:320,height:740}]){
  const context=await browser.newContext({viewport,ignoreHTTPSErrors:true,serviceWorkers:'block'}),p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));const base=process.env.TEST_APP_URL||'http://localhost:8768/';if(!process.env.TEST_APP_URL)await p.route(base+'**',r=>{const pathname=new URL(r.request().url()).pathname;return r.fulfill({path:path.join(__dirname,'..',pathname==='/'?'index.html':pathname),contentType:pathname.endsWith('.js')?'application/javascript':pathname.endsWith('.css')?'text/css':pathname.endsWith('.jpg')?'image/jpeg':'text/html'});});await p.goto(base);await p.waitForFunction(()=>typeof renderAdvisor==='function');
  async function nav(view){if(viewport.width>700)await p.locator(`.side nav [data-view="${view}"]`).click();else{await p.locator('#moreNav').click();await p.locator(`#menuDialog [data-view="${view}"]`).click();}}
  await p.evaluate(()=>show('trade'));assert.equal(await p.inputValue('#before'),'');assert.equal(await p.inputValue('#after'),'');assert.equal(await p.inputValue('#plan'),'');await nav('advisor');assert.match(await p.locator('#advisorDiscipline').innerText(),/Noch keine Trades/);assert.match(await p.locator('#advisorWeekly').innerText(),/Keine Trades/);
  const fixture=await p.evaluate(()=>{const a=crypto.randomUUID(),b=crypto.randomUUID();data.accounts=[{id:a,ownerId:data.ownerId,name:'Funded coach',max:2,daily:500},{id:b,ownerId:data.ownerId,name:'Challenge coach',max:5,daily:1000}];data.trades=Array.from({length:12},(_,i)=>({id:crypto.randomUUID(),ownerId:data.ownerId,accountId:a,date:'2026-10-0'+(5+i%5),market:'NQ',pnl:i%2?-200:50,risk:i%3?250:300,before:i%2?'FOMO':'Ruhig',plan:i===1?'Nein':'Ja',violation:i===1?'Overtrading':'',session:'London Opening',setup:'IFVG',preflight:Object.fromEntries(F.checklist.map(([k])=>[k,k!=='ifvg'||i%3!==0]))}));data.trades.push({id:crypto.randomUUID(),ownerId:data.ownerId,accountId:b,date:'2026-10-07',market:'ES',pnl:75,session:'New York Opening',before:'Ruhig',setup:'Other setup'});save();render();return {a,b};});
  await p.fill('#advisorWeek','2026-10-07');await p.locator('#advisorWeek').dispatchEvent('change');assert.match(await p.locator('#advisorSummary').innerText(),/13 Trades/);assert.match(await p.locator('#advisorDiscipline').innerText(),/Mehr Trades als geplant/);assert.match(await p.locator('#advisorEmotions').innerText(),/FOMO/);assert.match(await p.locator('#advisorSetups').innerText(),/nicht bestätigt/);assert.match(await p.locator('#advisorPatterns').innerText(),/BEOBACHTUNGSMUSTER/);assert.equal(await p.locator('#advisorWeekly .advisor-insight').count(),3);
  const evidence=p.locator('#advisorDiscipline .advisor-evidence').first();await evidence.locator('summary').click();await evidence.locator('[data-advisor-trade]').first().click();assert.equal(await p.locator('#tradeDetailDialog').isVisible(),true);assert.match(await p.locator('#tradeDetailBody').innerText(),/Feedback zu diesem Trade/);await p.keyboard.press('Escape');
  await p.selectOption('#advisorAccount',fixture.b);assert.match(await p.locator('#advisorSummary').innerText(),/1 Trade/);assert.doesNotMatch(await p.locator('#advisorEmotions').innerText(),/FOMO/);await p.selectOption('#advisorAccount',fixture.a);await p.fill('#advisorFrom','2026-10-08');await p.locator('#advisorFrom').dispatchEvent('change');await p.fill('#advisorTo','2026-10-09');await p.locator('#advisorTo').dispatchEvent('change');assert.match(await p.locator('#advisorSummary').innerText(),/4 Trades/);assert.match(await p.locator('#advisorWeekPeriod').innerText(),/12 Trades/);
  await p.fill('#advisorFrom','2026-10-10');await p.locator('#advisorFrom').dispatchEvent('change');assert.match(await p.locator('#advisorSummary').innerText(),/Enddatum/);assert.equal(await p.locator('#advisorDiscipline').innerHTML(),'');await p.getByRole('button',{name:'Gesamte Historie',exact:true}).click();
  await p.getByText('Deinen Coaching-Rahmen einstellen',{exact:true}).click();await p.fill('#advisorMax','4');await p.fill('#advisorRisk','100');await p.getByRole('button',{name:'Coaching-Rahmen speichern',exact:true}).click();assert.deepEqual(await p.evaluate(()=>data.profile.advisorRules),{maxPerDay:4,riskPerTrade:100});await p.reload();await p.waitForFunction(()=>typeof renderAdvisor==='function');await nav('advisor');await p.getByText('Deinen Coaching-Rahmen einstellen',{exact:true}).click();assert.equal(await p.inputValue('#advisorMax'),'4');assert.equal(await p.inputValue('#advisorRisk'),'100');await p.fill('#advisorRisk','75');await p.locator('#advisor h2').first().click();await p.evaluate(()=>renderAfterSync());assert.equal(await p.inputValue('#advisorRisk'),'75');
  await nav('daily');await p.fill('#weekDate','2026-10-07');await p.locator('#weekDate').dispatchEvent('change');assert.equal(await p.locator('#weeklyCoaching .advisor-insight').count(),3);await nav('advisor');
  for(const theme of ['dark','light']){await p.evaluate(t=>setTheme(t),theme);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${theme} coach ${viewport.width}px`);}
  await p.evaluate(()=>{window.injected=0;data.trades[0].before='<img src=x onerror="window.injected=1">';data.trades[0].setup='<svg onload="window.injected=1">';renderAdvisor();});assert.equal(await p.locator('#advisorEmotions img,#advisorPatterns svg').count(),0);assert.equal(await p.evaluate(()=>window.injected),0);
  if(viewport.width===390){await p.evaluate(()=>{setTheme('dark');document.getElementById('advisorRulesForm').closest('details').open=false;});await p.locator('.advisor-columns').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(__dirname,'../../advisor-mobile-check.png')});}
  await p.evaluate(()=>clearUser());assert.equal(await p.inputValue('#advisorAccount'),'');assert.equal(await p.inputValue('#advisorRisk'),'250');assert.doesNotMatch(await p.locator('#advisor').innerText(),/Funded coach|FOMO.*Trades/);assert.equal(await p.locator('#weeklyCoaching .advisor-insight').count(),0);assert.deepEqual(errors,[]);console.log(`PASS ${viewport.width}px: coaching evidence, five sections, account/date/week scope, rule persistence, dirty form, XSS and user reset`);await context.close();
}}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
