const test=require('node:test'),assert=require('node:assert/strict'),A=require('../journal-advisor.js'),F=require('../journal-features.js'),J=require('../sync-core.js');
const accounts=[{id:'a',name:'Funded',max:2,daily:500},{id:'b',name:'Challenge',max:4,daily:1000}];
const trade=(id,extra={})=>({id,date:'2026-10-07',accountId:'a',market:'NQ',pnl:100,risk:250,session:'London Opening',before:'Ruhig',plan:'Ja',preflight:Object.fromEntries(F.checklist.map(([k])=>[k,true])),...extra});
test('coach detects daily count, account limits, net daily loss and planned risk with exact evidence',()=>{const rows=[trade('1',{pnl:-300,risk:300}),trade('2',{pnl:-250}),trade('3',{pnl:10}),trade('4',{accountId:'b',pnl:1000})],copy=JSON.stringify(rows);const r=A.analyze(rows,accounts);assert.equal(r.issues.find(x=>x.key==='overtrading').ids.length,4);assert.equal(r.issues.find(x=>x.key==='account-count').ids.length,3);assert.deepEqual(r.issues.find(x=>x.key==='daily-loss').ids,['1','2','3']);assert.deepEqual(r.issues.find(x=>x.key==='risk').ids,['1']);assert.equal(JSON.stringify(rows),copy);assert.equal(r.actions.length,3);assert.equal(r.actions.filter(x=>['overtrading','account-count'].includes(x.key)).length,1);});
test('coach preserves missing data and does not infer setup quality from P&L',()=>{const r=A.analyze([trade('1',{pnl:-100,preflight:undefined,risk:null,before:''}),trade('2',{pnl:400,preflight:{bias:true,ifvg:false}})],accounts);const q=r.setup.find(x=>x.key==='ifvg');assert.equal(q.confirmed,0);assert.equal(q.open,1);assert.equal(q.unknown,1);assert.deepEqual(q.ids,['2']);assert.deepEqual(r.issues.find(x=>x.key==='setup').ids,['2']);assert.equal(r.coverage.preflight,0);assert.equal(r.coverage.risk,1);assert.equal(r.coverage.emotion,1);});
test('session checks use Berlin windows, exact boundaries and never fake imported midnight',()=>{const rows=['09:00','10:00','15:30','17:00','21:00','22:00'].map((time,i)=>trade(String(i),{time}));rows.push(trade('manual',{time:'',session:'London Opening'}),trade('csv',{time:'00:00',setup:'CSV-Import',session:'Außerhalb Session'}),trade('outside',{time:'',session:'Außerhalb Session'}));const r=A.analyze(rows,accounts);assert.deepEqual(r.issues.find(x=>x.key==='outside').ids,['1','3','5','outside']);assert.equal(r.coverage.time,6);});
test('emotion feedback counts documented trades and losses without attributing causation',()=>{const rows=[trade('1',{before:'FOMO',pnl:-100}),trade('2',{before:'FOMO',pnl:50}),trade('3',{before:'',pnl:-200}),trade('4',{before:'Ruhig',pnl:-25})],r=A.analyze(rows,accounts);assert.equal(r.emotions.find(x=>x.name==='FOMO').count,2);assert.equal(r.emotions.find(x=>x.name==='FOMO').losses,1);assert.deepEqual(r.issues.find(x=>x.key==='emotion').ids,['1','2']);assert.match(r.issues.find(x=>x.key==='emotion').evidence,/keine Ursache/);assert.ok(r.emotions.every(x=>!x.sufficient));});
test('patterns require ten trades across five days, including per-account/date scoping',()=>{const rows=Array.from({length:10},(_,i)=>trade(String(i),{date:'2026-10-0'+(5+i%5),pnl:-10}));const r=A.analyze(rows,accounts);assert.ok(r.patterns.find(x=>x.dimension==='setup').sufficient);assert.ok(r.issues.some(x=>x.key==='pattern'));assert.ok(A.analyze(rows.map(t=>({...t,date:'2026-10-07'})),accounts).patterns.every(p=>!p.sufficient));const filtered=A.analyze([...rows,trade('foreign',{accountId:'b'}),trade('deleted',{accountId:'x'})],accounts,{account:'a',from:'2026-10-08',to:'2026-10-09'});assert.equal(filtered.rows.length,4);assert.equal(filtered.metrics.pnl,-40);assert.ok(filtered.rows.every(t=>t.accountId==='a'));});
test('weekly coach returns three distinct steps and does not invent evidence for empty weeks',()=>{const week=F.week('2026-10-07'),r=A.analyze([trade('1')],accounts,{from:week.start,to:week.end});assert.equal(r.actions.length,3);assert.equal(new Set(r.actions.map(x=>x.key)).size,3);assert.ok(r.actions.every(x=>x.ids.every(id=>id==='1')));assert.ok(A.analyze([],accounts).actions.every(x=>x.ids.length===0));});
test('coaching rules merge across devices without changing trades or reviews',()=>{const base=J.empty('u');base.profile.advisorRules={maxPerDay:2,riskPerTrade:250};const l=J.clone(base),r=J.clone(base);l.profile.advisorRules.maxPerDay=3;r.profile.advisorRules.riskPerTrade=200;const merged=J.normalize(J.merge(base,l,r),'u');assert.deepEqual(merged.profile.advisorRules,{maxPerDay:3,riskPerTrade:200});assert.deepEqual(merged.trades,[]);assert.deepEqual(merged.reviews,{});assert.deepEqual(A.rules({maxPerDay:-2,riskPerTrade:'NaN'}),A.defaults);});

test('per-trade coaching includes the selected day across accounts and never an unrelated date',()=>{
 const rows=[trade('first'),trade('second',{accountId:'b'}),trade('saved',{before:'FOMO',risk:300,pnl:200}),trade('yesterday',{date:'2026-10-06',risk:999,before:'Revenge'})];const f=A.feedback('saved',rows,accounts);assert.equal(f.dayCount,3);assert.equal(f.accountDayCount,2);assert.ok(f.issues.some(i=>i.key==='overtrading'));assert.ok(f.issues.some(i=>i.key==='risk'));assert.ok(f.issues.some(i=>i.key==='emotion'));assert.ok(f.issues.every(i=>!i.ids.includes('yesterday')));assert.match(f.overview,/Auffälligkeiten/);assert.equal(A.feedback('missing',rows,accounts),null);
});
test('a documented compliant loss receives process feedback, not a fabricated strategy error',()=>{
 const f=A.feedback('loss',[trade('loss',{pnl:-100})],accounts);assert.equal(f.issues.length,0);assert.equal(f.missing.length,0);assert.match(f.overview,/Verlust allein/);assert.equal(f.confirmed,8);assert.ok(f.positives.some(p=>p.includes('Risiko')));assert.match(f.next,/Setup-Prüfung/);
});
test('incomplete per-trade records expose unknowns and edited records use the current values',()=>{
 const t=trade('edit',{risk:null,before:'',plan:'',preflight:undefined});const f=A.feedback(t.id,[t],accounts);assert.ok(f.missing.includes('Emotion vor dem Einstieg'));assert.ok(f.missing.some(s=>s.includes('unbekannte Setup-Checks')));assert.equal(f.confirmed,0);const edited={...t,risk:500};assert.ok(A.feedback(t.id,[edited],accounts).issues.some(i=>i.key==='risk'));assert.deepEqual(t.risk,null);
});
