const test=require('node:test'),assert=require('node:assert/strict'),F=require('../journal-features.js'),J=require('../sync-core.js');
const trades=[100,-40,-60,0,200,-50].map((pnl,i)=>({id:String(i),date:'2026-10-0'+(i+1),time:'15:30',accountId:'a',market:'NQ',direction:'LONG',pnl,risk:i===0?50:undefined}));
test('net risk analytics never invent missing R; chronology controls drawdown and streak',()=>{const m=F.metrics([...trades].reverse());assert.equal(m.pnl,150);assert.equal(m.drawdown,100);assert.equal(m.maxLossStreak,2);assert.equal(m.profitFactor,2);assert.equal(m.expectancy,25);assert.equal(m.averageR,2);assert.equal(m.rCount,1);assert.equal(F.multiple({pnl:10,risk:0}),null);assert.equal(F.metrics([]).expectancy,null);});
test('calendar weeks include Sunday and ignore DST transitions',()=>{assert.deepEqual(F.week('2026-10-25'),{start:'2026-10-19',end:'2026-10-25'});assert.equal(F.validDate('2026-02-30'),false);assert.equal(F.weekTrades(trades,'2026-10-06').length,2);});
test('challenge uses account/cycle, positive qualifying days and documented payouts',()=>{const q=F.tracker({id:'a',size:50000,cycleStart:'2026-10-02',qualifyingDayTarget:100,requiredDays:3,profitTarget:3000,payouts:{p:{id:'p',amount:75,date:'2026-10-05'}}},[...trades,{...trades[0],accountId:'b',pnl:99999}]);assert.equal(q.pnl,50);assert.equal(q.qualifying,1);assert.equal(q.balance,50075);assert.equal(q.payoutTotal,75);assert.equal(q.target,3000);});
test('CSV supports BOM, German values, quoted multiline notes, mapping, errors and duplicates',()=>{const parsed=F.csv('\uFEFFDatum;Uhrzeit;Markt;Richtung;P&L;Risiko;Gebühren;Notiz;TradeId\r\n06.10.2026;15:35;NQ;BUY;"1.250,50";250;5;"Line 1\nLine ""2""";abc\r\n06.10.2026;15:35;NQ;BUY;"1.250,50";250;5;duplicate;abc\r\n30.02.2026;10:00;ES;SELL;50;20;0;invalid;x');const m=F.guess(parsed.headers),r=F.importRows(parsed,m,'a',[],{gross:true});assert.equal(r.trades.length,1);assert.equal(r.trades[0].pnl,1245.5);assert.equal(r.trades[0].note,'Line 1\nLine "2"');assert.deepEqual(r.duplicates,[3]);assert.equal(r.errors[0].row,4);assert.equal(F.importRows(parsed,m,'a',r.trades,{gross:true}).trades.length,0);assert.equal(F.importRows(parsed,m,'b',r.trades,{gross:true}).trades.length,1);});
test('CSV semantic duplicate detection, required mapping and empty/malformed files',()=>{const p=F.csv('Datum,Markt,P&L\n2026-10-06,NQ,100\n2026-10-06,NQ,100');const m=F.guess(p.headers);assert.equal(F.importRows(p,m,'a',[]).duplicates.length,1);assert.throws(()=>F.importRows(p,{date:-1,market:1,pnl:2},'a',[]));assert.throws(()=>F.csv('a,a\n1,2'));assert.throws(()=>F.csv('a,b\n"x,y'));assert.equal(F.number('($1,250.25)'),-1250.25);assert.equal(F.filter(trades,{setup:'IFVG'}).length,6);assert.equal(F.filter(trades,{search:'short'}).length,0);});
test('concurrent phone/laptop goals, payouts and weekly reviews merge independently',()=>{const id='aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa',base={...J.empty('u'),accounts:[{id,ownerId:'u',name:'A',payouts:{}}],reviews:{}};const l=J.clone(base),r=J.clone(base);l.accounts[0].profitTarget=3000;l.accounts[0].payouts.p={id:'p',amount:100};r.accounts[0].requiredDays=5;r.accounts[0].payouts.q={id:'q',amount:200};l.reviews['2026-10-05']={reflection:'phone'};r.reviews['2026-10-12']={focus:'laptop'};const merged=J.merge(base,l,r);assert.equal(merged.accounts[0].profitTarget,3000);assert.equal(merged.accounts[0].requiredDays,5);assert.equal(Object.keys(merged.accounts[0].payouts).length,2);assert.equal(Object.keys(merged.reviews).length,2);});
test('malformed new workflow backups are rejected before replacing saved journal',()=>{const b=J.empty('u');b.reviews=[];assert.throws(()=>J.normalize(b,'u'));const a=J.empty('u');a.accounts=[{id:'aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa',payouts:{p:{id:'p',date:'2026-10-06',amount:-100}}}];assert.throws(()=>J.normalize(a,'u'));});
