const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path');
(async()=>{const proxy=process.env.HTTPS_PROXY||process.env.HTTP_PROXY;const browser=await chromium.launch({args:['--no-sandbox'],...(proxy?{proxy:{server:proxy}}:{})});try{for(const viewport of [{width:1440,height:900},{width:390,height:844},{width:320,height:740}]){
 const c=await browser.newContext({viewport,ignoreHTTPSErrors:true,serviceWorkers:'block'}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));const base=process.env.TEST_APP_URL||'http://localhost:8769/';if(!process.env.TEST_APP_URL)await p.route(base+'**',r=>{const n=new URL(r.request().url()).pathname;return r.fulfill({path:path.join(__dirname,'..',n==='/'?'index.html':n),contentType:n.endsWith('.js')?'application/javascript':n.endsWith('.css')?'text/css':n.endsWith('.jpg')?'image/jpeg':'text/html'});});await p.goto(base);await p.waitForFunction(()=>typeof openTradeFeedback==='function');
 const account=await p.evaluate(()=>{const id=crypto.randomUUID();data.accounts=[{id,ownerId:data.ownerId,name:'Automatic feedback account',max:10,daily:500}];save();render();show('trade');return id;});
 async function fillTrade(pnl,{risk=250,emotion='Ruhig',plan='Ja',complete=true}={}){await p.evaluate(()=>show('trade'));await p.selectOption('#accT',account);await p.fill('#pnl',String(pnl));if(risk!==null)await p.fill('#riskT',String(risk));await p.selectOption('#before',emotion);await p.selectOption('#plan',plan);await p.selectOption('#sessionT','London Opening');if(complete)for(const key of ['bias','zone','sweep','internal','ifvg','smt','cisd','target'])await p.check('#preflight-'+key);}
 const dialog=p.locator('#tradeFeedbackDialog');await fillTrade(-100);await p.getByRole('button',{name:'Trade speichern',exact:true}).click();await dialog.waitFor({state:'visible'});assert.equal(await p.evaluate(()=>data.trades[0].pnl),-100);assert.match(await p.locator('#tradeFeedbackBody').innerText(),/Verlust allein/);assert.match(await p.locator('#tradeFeedbackMeta').innerText(),/100,00/);await p.keyboard.press('Escape');assert.equal(await dialog.isVisible(),false);assert.equal(await p.evaluate(()=>data.trades.length),1);
 await fillTrade(50,{risk:300,emotion:'FOMO',plan:'Nein',complete:false});await p.getByRole('button',{name:'Trade speichern',exact:true}).click();await dialog.waitFor({state:'visible'});assert.match(await p.locator('#tradeFeedbackBody').innerText(),/Risiko über deinem Rahmen/);assert.match(await p.locator('#tradeFeedbackBody').innerText(),/Emotionale Einstiege/);assert.match(await p.locator('.feedback-next').innerText(),/Positionsgröße/);await dialog.getByRole('button',{name:'Trade ansehen',exact:true}).click();await p.getByRole('button',{name:'Trade bearbeiten',exact:true}).click();await p.fill('#riskT','100');await p.selectOption('#before','Ruhig');await p.selectOption('#plan','Ja');for(const key of ['bias','zone','sweep','internal','ifvg','smt','cisd','target'])await p.check('#preflight-'+key);await p.getByRole('button',{name:'Trade speichern',exact:true}).click();await dialog.waitFor({state:'visible'});assert.equal(await p.evaluate(()=>data.trades.length),2);assert.doesNotMatch(await p.locator('#tradeFeedbackBody').innerText(),/Risiko über deinem Rahmen|Emotionale Einstiege/);await p.locator('#tradeFeedbackClose').click();
 await fillTrade(-20);await p.getByRole('button',{name:'Trade speichern',exact:true}).click();await dialog.waitFor({state:'visible'});assert.match(await p.locator('#tradeFeedbackBody').innerText(),/Mehr Trades als geplant/);assert.match(await p.locator('#tradeFeedbackBody').innerText(),/3 Trades über alle Konten/);for(const theme of ['dark','light']){await p.evaluate(t=>setTheme(t),theme);assert.ok(await dialog.evaluate(e=>e.scrollWidth<=e.clientWidth+2));assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}if(viewport.width===390){await p.evaluate(()=>setTheme('dark'));await p.screenshot({path:path.join(__dirname,'../../automatic-feedback-mobile.png')});}
 await dialog.getByRole('button',{name:'Journal-Coach öffnen',exact:true}).click();assert.equal(await p.locator('#advisor').isVisible(),true);assert.equal(await dialog.isVisible(),false);await p.evaluate(()=>openTradeFeedback(data.trades[2].id));assert.equal(await dialog.isVisible(),true);await p.evaluate(()=>clearUser());assert.equal(await dialog.isVisible(),false);assert.equal(await p.locator('#tradeFeedbackBody').innerHTML(),'');assert.equal(await p.locator('#tradeFeedbackMeta').innerText(),'');assert.equal(await p.evaluate(()=>tradeFeedbackContext),null);
 // A failed save must not open a success-coaching dialog.
 await p.evaluate(id=>{data.accounts=[{id,ownerId:data.ownerId,name:'Unsaved',max:10}];render();window.realSave=save;save=()=>false;},account);await fillTrade(25);await p.getByRole('button',{name:'Trade speichern',exact:true}).click();assert.equal(await dialog.isVisible(),false);await p.evaluate(()=>save=realSave);assert.deepEqual(errors,[]);console.log(`PASS ${viewport.width}px: automatic post-save coaching, compliant loss, risk/emotion feedback, edit refresh, daily context, dialog actions, failed save and user reset`);await c.close();
}}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
